export const LOGIN = "login_demo";
export const SOCIAL_APP = "socialapp";
export const REGISTER = "register_demo"
export const SEND_OTP = "send_otp_demo"
export const VERIFY_OTP = "verify_otp_demo"
export const HOMETAB = "tab";
export const HOMENEWS = "home_news";
export const NEWS = "news";
export const FORUM = "forum";
export const FORUMDISCUSSION = "forum/detail";
export const FORUM_CREATE = "forum/create";
export const GET_PROFILE = "user_det";
export const UPDATE_PROFILE = "up_user_det";
export const CHANGE_PASSWORD = "change_password_user_demo";
export const UPDATE_PROFILE_PIC = "profile_pic_update";
export const FORGOT_PASSWORD = "forgetpw_demo";
export const FORGOT_VERIFY_OTP = "verify_otp_demo";
export const RESET_PASSWORD_DEMO = "reset_password_demo";
export const CALENDARTAB = "event_schedule ";
export const FEEDBACK = "create_feedback ";
export const USERLEVEL = "hashtag_app_redirect";
